services:
  odoo:
    container_name: odoo_${PROJECT}
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "127.0.0.1:${PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
    networks:
      - saas_network
    environment:
      - HOST=db_${PROJECT}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
  db:
    container_name: db_${PROJECT}
    image: postgres:15
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - saas_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  saas_network:
    external: true
