services:
  odoo:
    container_name: odoo_test2
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      # - ./addons:/mnt/extra-addons
    networks:
      - saas_network
    restart: always
  db:
    container_name: db_test2
    image: postgres:15
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - saas_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odooPassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  saas_network:
    external: true
